FLS-813: HSRA Eligibility Forms updated
communitiesuk/digital-form-builder-adapter pull request #73
Opened 2024-11-28 08:47 UTC by hamzabinkhalid

https://mhclgdigital.atlassian.net/browse/FLS-813

### Change description
- Updated eligibility forms
- Added new forms with eligibility question and logic for HSRA redirect to round based on eligibility question

- [X] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
- Make sure HSRA VR/RP are live
- Go through the login process
- Click on check eligibility button
- Make sure selecting vacancy register or refurbishment project as answer to question "Why are you applying to this funding?" forwards you to the correct Application tasklist for that round

### Screenshots of UI changes (if applicable)

2024-11-29 09:28 UTC, nuwan-samarasinghe requested changes

2024-11-29 10:32 UTC, sfount commented on runner/src/server/plugins/engine/page-controllers/ConfirmPageController.ts
> +                round_name = state["mwumLN"]["OjGBLs"];
👍 outside of a prototype I think we'll want this to work as predictably as possible as well so I think its OK to apply to any fund as long as its configured for it.

The ticket mentions it working similarly to the `markAsComplete` sections which get added but are treated uniquely by the code.

Something like:
```javascript
const redirectToEligibleRound = state["redirectToEligibleRound"]

const url = new URL(`/${fund_name}/${round_name}`, config.eligibilityResultUrl)


if (redirectToEligibleRound) {
  // include the appropriate round to redirect to if it was included in the funds eligibility questions
  url.searchParams.set('redirect_to_eligible_round', redirectToEligibleRound)
}

return redirectTo(request, h, url.href)
```

2024-11-29 10:34 UTC, sfount reviewed
Really impressive proving the concept and getting the configuration started! Outside of the prototype I think it would be good if the redirect feature could be split out into another PR to make the git history a bit easier to follow and so people can review the two changes separately

2024-12-03 15:44 UTC, nuwan-samarasinghe submitted a review, later dismissed
LGTM

for HSRA config are we not using FAB

2024-12-04 14:01 UTC, hamzabinkhalid commented
> LGTM
> 
> for HSRA config are we not using FAB

No, Since we already had HSRA configs in the codebase, trying to update those for the new requirements

2024-12-09 14:19 UTC, sfount approved these changes

2024-12-09 15:07 UTC, merged