Fs 4940 sentry implementation
communitiesuk/digital-form-builder-adapter pull request #95
Opened 2024-12-31 16:13 UTC by nuwan-samarasinghe

**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4940**

### Change description
Implementing Sentry to monitor errors

- [x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

2025-01-02 14:30 UTC, NarenderRajuB approved these changes
LGTM

2025-01-02 15:11 UTC, wjrm500 requested changes
I notice that in the new Form Runner Sentry project we have no alert rules configured:

![image](https://github.com/user-attachments/assets/4403e33e-338d-485f-a747-aa3f1ceca3ec)

We need alert rules to trigger Slack messages on errors, which is a key part of the flow. See other projects in Sentry for example alert rules.

Once these alert rules have been configured, could you provide some simple testing instructions we can use to verify that the PR changes are working as intended - thanks

2025-01-02 15:38 UTC, wjrm500 commented
@nuwan-samarasinghe - follow-up comment - from the [Sentry documentation for Hapi integration](https://docs.sentry.io/platforms/javascript/guides/hapi/) (thanks @samuelhwilliams for pointing me to this), we have a more concise implementation documented as the exemplar, including this lovely command:

`await Sentry.setupHapiErrorHandler(server);`

This would mean no need for manual onPreResponse changes. Can we use this?

2025-01-03 11:49 UTC, wjrm500 commented
Nice thanks for making that change @nuwan-samarasinghe, could you provide brief testing instructions so we can see that this works as intended?

2025-01-03 14:35 UTC, nuwan-samarasinghe commented
I have gone through the hapi documentation and found the following `await Sentry.setupHapiErrorHandler(server);` this will trigger once you are using the hapi error handler but we are attaching the errors into the response it self then server will not have any context about the errors and error handling will be done on the browser 

Ex. 

throw new Error('Something went wrong'); -> these will be captured using `Sentry.setupHapiErrorHandler(server);`

but,

return h.response({ error: 'Something went wrong' }).code(500); and throw Boom.unauthorized("publishing is disabled"); handled in response side 

For this I am using the both ways then we can cover all the issues

2025-01-07 08:16 UTC, nuwan-samarasinghe commented
-- Now the implementation is following 

Since we are using library related implementation we are unable to change the parent implementation to change the environments from development, test, production into dev, test, uat, prod for the sentry we have added a new variable to differentiate the environments since we have more environments.

### Testing steps :

Give basic auth for the following link : https://forms.dev.access-funding.test.levellingup.gov.uk
This should throw an unauthenticated error as following 

 
![image](https://github.com/user-attachments/assets/bca5c047-2fbc-45f7-9d67-9e6e32d47c4f)

2025-01-07 08:43 UTC, samuelhwilliams requested changes

2025-01-07 08:43 UTC, samuelhwilliams commented on runner/src/server/index.ts
> +    if (config.sentryDsn && config.sentryTracesSampleRate && config.sentryDsn.trim().length > 0 && config.sentryTracesSampleRate.trim().length > 0) {
It should be possible to initialise Sentry without a traces sample rate set - that is optional configuration. I think we should only check for `config.sentryDsn` being set here, and sentryTracesSampleRate can default to zero if unset.

2025-01-07 08:43 UTC, samuelhwilliams commented on runner/src/server/index.ts
> +        console.log(`DSN Available`);
Can we log this all in a single message please? I think this app tends to be very spammy with logs, which doesn't make it easier to trace requests and see what's going on. It would be nice to log fewer, more useful messages.

2025-01-07 08:43 UTC, samuelhwilliams commented on runner/src/server/index.ts
> +const Sentry = require('@sentry/node');
The documentation for Sentry says to create an `instrument.js` file and require/include/import that first, so that it can instrument all other modules.

Please can we follow the Sentry documentation around how to configure the app - unless we have a good reason to do it differently? https://docs.sentry.io/platforms/javascript/guides/hapi/#configure

2025-01-07 08:43 UTC, samuelhwilliams commented on runner/src/server/index.ts
> +                Sentry.captureException(response);
I don't know much about how hapi works, so this might be a dumb question but - do we definitely need to do this? I would have thought that Sentry automatically ties in to responses correctly. Is there a chance this will cause errors to actually be captured twice?

2025-01-07 08:47 UTC, samuelhwilliams commented on runner/src/server/index.ts
> +                Sentry.captureException(response);
https://github.com/getsentry/sentry-javascript/pull/11151 seems to agree?

> After checking the behaviour, it seems to me that we don't need to capture any Boom responses, as the errors that may cause a 5xx response are already captured by the core logic.

Are you able to confirm/refute please? :)

2025-01-07 09:16 UTC, nuwan-samarasinghe commented on copilot/fsd-form-runner-adapter/manifest.yml
> -  NODE_ENV: production
This is a different issue @samuelhwilliams in the original Xgovforms they have forced in the code to use the following schema otherwise we have to lot of code copy into our repository to fix this 

```
env: joi
        .string()
        .valid("development", "test", "production")
        .default("development"),
```

2025-01-07 09:31 UTC, nuwan-samarasinghe commented on runner/src/server/index.ts
> +    if (config.sentryDsn && config.sentryTracesSampleRate && config.sentryDsn.trim().length > 0 && config.sentryTracesSampleRate.trim().length > 0) {
Updated :)

2025-01-07 09:31 UTC, nuwan-samarasinghe commented on runner/src/server/index.ts
> +        console.log(`DSN Available`);
Updated

2025-01-07 09:31 UTC, samuelhwilliams commented on copilot/fsd-form-runner-adapter/manifest.yml
> -  NODE_ENV: production
oh no :(

2025-01-07 09:31 UTC, nuwan-samarasinghe commented on runner/src/server/index.ts
> +const Sentry = require('@sentry/node');
Added the change but need to test let me check will it work or not

2025-01-07 09:32 UTC, nuwan-samarasinghe commented on runner/src/server/index.ts
> +                Sentry.captureException(response);
https://github.com/communitiesuk/digital-form-builder-adapter/pull/95#issuecomment-2569314583

here I have mentioned unfortunately we have to use all our error handling is happening using boom

2025-01-07 09:36 UTC, samuelhwilliams commented on runner/src/server/index.ts
> +                Sentry.captureException(response);
<img width="478" alt="image" src="https://github.com/user-attachments/assets/b807fa2a-f489-4d47-b47a-3ef1aaccf78a" />

Just having a quick gander through our code at what errors we throw using boom. These mostly look like 4xx codes - do you think we want sentry to be reporting and alerting on these?

Maybe we can filter out 4xx errors here and only capture and report 5xx ones?

2025-01-07 10:55 UTC, nuwan-samarasinghe commented on runner/src/server/index.ts
> +                Sentry.captureException(response);
yes @samuelhwilliams thats my plan filter and report only 5** not 4** this will be a next PR

2025-01-07 10:56 UTC, nuwan-samarasinghe commented on runner/src/server/index.ts
> +                Sentry.captureException(response);
Also some of these need to be changed to 5** if needed

2025-01-07 13:55 UTC, samuelhwilliams commented on copilot/fsd-form-runner-adapter/manifest.yml
> +      SENTRY_ENV: dev
Can we do this just once at the top-level with `SENTRY_ENV: ${COPILOT_ENVIRONMENT_NAME}`?

2025-01-07 13:56 UTC, samuelhwilliams commented on runner/src/instrument.ts
> +        environment: config.sentryEnv || "prod" // Use the provided environment or default to "prod"
I'm not convinced about a default value here being prod - maybe it should be `development`? Or just no default value and we only initialise if both sentryDsn and sentryEnv are set?

2025-01-07 14:10 UTC, samuelhwilliams requested changes
I've been testing this locally and it's starting to look and feel right - nice work and thanks for persevering :) Thanks for refactoring as well and following the Sentry docs - having a more standard setup should make it easier to keep in sync with any changes they want us to make in the future.

One more comment around ignoring 4xx by default, by then I think this is about ready to go in.

2025-01-07 14:10 UTC, samuelhwilliams commented on runner/src/server/index.ts
> +                Sentry.captureException(response);
I am nervous of having too many noisy errors in our deployed environments.

Can we please only capture hapi boom exceptions with a statusCode >= 500 to start with.

Then I think you could make a ticket on your team's board to review any <500 exceptions (eg 404s on forms) and decide whether we want to log those appropriately - but let's please take a cautious approach :)

2025-01-07 14:30 UTC, nuwan-samarasinghe commented on runner/src/instrument.ts
> +        environment: config.sentryEnv || "dev" // Use the provided environment or default to "dev"
Fixed

2025-01-07 14:30 UTC, nuwan-samarasinghe commented on copilot/fsd-form-runner-adapter/manifest.yml
> +      SENTRY_ENV: dev
Fixed

2025-01-07 16:29 UTC, nuwan-samarasinghe commented
Fixed the Issue and deployed  to dev 

![image](https://github.com/user-attachments/assets/c8f0459b-21e9-4716-a1c0-aba34aa970b2)

2025-01-07 17:01 UTC, samuelhwilliams approved these changes
I think this looks good now - nice work, let's try it out 🎉

2025-01-07 17:32 UTC, merged